best <- function(state, outcome) {
  ## Read outcome data
  ## Check that state and outcome are valid
  ## Return hospital name in that state with lowest 30-day death
  ## rate
  
    if (!(outcome %in% c("pneumonia", "heart attack","heart failure"))) {
      stop("invalid outcome")

    }

    #We first read the data file
    x <- read.csv("rprog_data_ProgAssignment3-data/outcome-of-care-measures.csv", colClasses = "character")
    #We extract only the frames we care about converting them to numeric data
    y <- suppressWarnings(
            data.frame(
              x$Hospital.Name,
              x$State,
              as.numeric(x$Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia),
              as.numeric(x$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack),
              as.numeric(x$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure)
            )
          )
    #Simplify names
    colnames(y) <- c("Hosp.Name","State","Pneumonia","Heart.Attack","Heart.Failure")
    
    #Generate a list containing a data frame for each state
    my.data.list.by.state <- split(y,y$State)
    
    #We define a function to return a data frame with the hospital name with the best rate for each cause of death we care about
    #This function will be used with mapply
    find.min.hospital <- function(cStateData) {
      #Each of the minimum variables below is generated by finding the rows with mortality values = to the minimum value in the column we care about
      #The subset function returns those rows. We pull a vector of the hospital names from those rows, and then grab the first one in alphabetical
      #order by using the min function
      my.min.pneu <- min(as.character(subset(cStateData,min(cStateData$Pneumonia,na.rm = TRUE) == cStateData$Pneumonia)$Hosp.Name))
      my.min.ha <- min(as.character(subset(cStateData,min(cStateData$Heart.Attack,na.rm = TRUE) == cStateData$Heart.Attack)$Hosp.Name))
      my.min.hf <- min(as.character(subset(cStateData,min(cStateData$Heart.Failure,na.rm = TRUE) == cStateData$Heart.Failure)$Hosp.Name))
      #We build a one row matrix with the hospital names we just figured out and the state they are sited in
      my.return.matrix <- matrix(c(head(as.character(cStateData$State),1),my.min.pneu,my.min.ha,my.min.hf),nrow = 1)
      #We then build a data frame that has one observation based on this matrix
      my.return.data <- data.frame(my.return.matrix)                       
      colnames(my.return.data) <- c("State","pneumonia", "heart attack","heart failure")
      
      #we return this data frame, consisting of a single observation of a State, and the hospitals with the lowest mortality rates for the 3 conditions
      my.return.data
    }
    
    #We apply this function on all the data frames in the list
    result.list <- lapply(my.data.list.by.state,find.min.hospital)
    
    #We then merge the results
    outcome.of.care.data <- Reduce(rbind,result.list)
    
    #Now we can 
    if (!(state %in% end.result$State)) {
      stop("invalid state")
    }   
  
  as.character(outcome.of.care.data[outcome.of.care.data$State==state,outcome])
}